[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Harald Kr√§mer <tetha42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"lazy_static" = "1.4.0"
"regex" = "1.4.2"
"itertools" = "0.9.0"